# Generated by Django 3.2.15 on 2023-01-17 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(default=datetime.datetime(2023, 2, 16, 15, 3, 17, 897463))),
                ('expire_year', models.DateField(default=datetime.datetime(2024, 1, 17, 15, 3, 17, 897463))),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.plan')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
