# Generated by Django 3.2.15 on 2023-01-17 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20230117_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 15, 10, 10, 350791)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_year',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 15, 10, 10, 350791)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 15, 10, 10, 350791)),
        ),
    ]
