# Generated by Django 3.2.15 on 2023-01-17 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20230117_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_ammount',
            new_name='payment_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 15, 10, 30, 895450)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_year',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 15, 10, 30, 895450)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 15, 10, 30, 895450)),
        ),
    ]
