# Generated by Django 3.2.15 on 2023-01-17 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20230117_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 15, 30, 14, 921533)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire_year',
            field=models.DateField(default=datetime.datetime(2024, 1, 17, 15, 30, 14, 921533)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 15, 30, 14, 921533)),
        ),
    ]
