# Generated by Django 3.2.15 on 2023-01-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('website', models.URLField(blank=True)),
                ('password', models.CharField(max_length=12)),
                ('active', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
