# Generated by Django 3.2.15 on 2023-01-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('user', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
